CREATE TABLE IF NOT EXISTS `tse_listings` (
  `code` VARCHAR(8) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `market` VARCHAR(255) NOT NULL,
  `sector33_code` VARCHAR(16) NOT NULL,
  `sector33_name` VARCHAR(255) NOT NULL,
  `sector17_code` VARCHAR(16) NOT NULL,
  `sector17_name` VARCHAR(255) NOT NULL,
  `scale_code` VARCHAR(16) NOT NULL,
  `scale_name` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
